baseURL: "https://blog-innocraft-colman.web.app"
languageCode: "en-us"
title: "< CODEMAN />"
theme: "hugo-PaperMod"

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  disqus: "codeman"
  profileMode:
    enabled: true,
    subtitle: ""
    title: "BLOG â€¢ CODE â€¢ ğŸ±â€ğŸ"
    imageUrl: "/icon.png"
    imageTitle: "CodeMan Logo"
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: ğŸª Visit Portfolio
        url: "https://colman.tk"
  socialIcons:
    - name: "github"
      url: "https://github.com/colman1000"
    - name: "linkedin"
      url: "https://linkedin.com/in/colman1000"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/12045807/colman1000"
    - name: "twitter"
      url: "https://twitter.com/colman_1000"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  comments: true

  editPost:
    URL: "https://github.com/Colman1000/blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  ShowPostNavLinks: true

menu:
  main:
#    - identifier: portfolio
#      name: Portfolio
#      pre: ğŸª
#      url: https://colman.tk
#      weight: 40
    - identifier: articles
      name: Articles
      pre: ğŸ€„
      url: /articles
      weight: 10
    - identifier: categories
      name: Categories
      pre: ğŸ¯
      url: /categories/
      weight: 20
    - identifier: search
      name: Search
      pre: ğŸ”
      url: /search/
      weight: 30



#ğŸ”ğŸ”–
